export default {
    nota: ['toca 60', 'espera 1'],
    arpejoDo: [
        'toca do3',
        'espera 1',
        '',
        'toca mi3',
        'espera 1',
        '',
        'toca sol3',
        'espera 1',
    ],
    acordeDo: ['toca do3', 'toca mi3', 'toca sol3'],
    cromatico: [
        'toca do',
        'espera 0.25',
        'toca do#',
        'espera 0.25',
        'toca re',
        'espera 0.25',
        'toca re#',
        'espera 0.25',
        'toca mi',
        'espera 0.25',
        'toca re#',
        'espera 0.25',
        'toca re',
        'espera 0.25',
        'toca do#',
        'espera 0.25',
    ],
}
